SELECT 
C.APNT_NO,
A.PT_NAME,
C.PT_NO,
C.MCDP_CD,
B.DR_NAME,
C.APNT_YMD
FROM APPOINTMENT C
JOIN DOCTOR B ON C.MDDR_ID = B.DR_ID
JOIN PATIENT A ON A.PT_NO = C.PT_NO
WHERE C.APNT_YMD LIKE '2022-04-13%' 
AND C.APNT_CNCL_YN = 'N'
AND C.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD